Models/Kullanici.cs
using System.ComponentModel.DataAnnotations;

namespace intro_LoginExam_v1.Models
{
	public class Kullanici : BaseObject
	{
		[Required(ErrorMessage = "{0} boş geçilemez.")]
		[Display(Name = "Ad Soyad")]//grid de görünecek ya da edit sayfasında görünecek label üzerinde yazan yazı
		[StringLength(50, ErrorMessage = "{0} alanı en fazla {1} karakter olabilir")]
		public string AdSoyad { get; set; }

		[Required(ErrorMessage = "{0} boş geçilemez.")]
		[Display(Name = "E-Mail")]
		[StringLength(50, ErrorMessage = "{0} adresi en fazla {1} karakterden oluşabilir.")]
		//	[DataType(DataType.EmailAddress)]
		[EmailAddress]
		public string EMail { get; set; }

		[Display(Name = "Kullanıcı Kodu")]
		[Required(ErrorMessage = "{0} alanı boş olamaz.")]
		[StringLength(10, ErrorMessage = "{0} en fazla {1} karakterden oluşabilir.")]

		public string KullaniciKodu { get; set; }

		[Display(Name = "Şifre")]
		[Required(ErrorMessage = "{0} alanı boş olamaz.")]
		[DataType(DataType.Password)]
		//en az 2 rakam, maks 10 elamn, min 1 tane özel , min 1 büyük harf
		//[RegularExpression(@"^(?=(.*\d){2,})(?=.*[\W_])(?=.*[A-Z]).{1,10}$",ErrorMessage ="Kullanıcı şifre hatalı")]
		[StringLength(10, ErrorMessage ="{0} alanı {1} karakterden az olamaz.")]
		public string KullaniciSifre { get; set; }

		[Display(Name = "Yaş")]
		[RegularExpression("^[0-9]+$", ErrorMessage ="{0} alanına sadece sayısal değer yazabilirsiniz.")]
		[Required (ErrorMessage ="{0} boş geçilemez.")]
		[Range(18,180,ErrorMessage ="{0} en az 18 olmalı.")]
		public string Yas { get; set; }//565464654


	}
}

Controllers/KullaniciController.cs
using intro_LoginExam_v1.Context;
using intro_LoginExam_v1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace intro_LoginExam_v1.Controllers
{
	public class KullaniciController : Controller
	{

		private readonly DataContext _dataContext;

		public KullaniciController(Context.DataContext dataContext)
		{
			_dataContext = dataContext;
		}

		public IActionResult Index()
		{
			var kullanici = _dataContext.Kullanici.ToList();

			return View(kullanici);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		/// <summary>
		/// Edit işleminin yapılacağı sayfayı son kullanıcının önüne çıkarmak için gerekli fonksiyon
		/// </summary>
		/// <param name="id">Editlenecek kullanıcının primary Key'i</param>
		/// <returns>ekrana, web sayfası içinde kullanıcı bilgilerini atması/fırlatması gerekiyor.</returns>
		public IActionResult Edit(int? id)
		{
			if (id is null)
				return RedirectToAction(nameof(Index));

			var edit = _dataContext.Kullanici.Where(e => e.Id == id).FirstOrDefault();
			if (edit is null)
				return RedirectToAction(nameof(Index));

			return View(edit);
		}

		[HttpPost]
		public IActionResult Edit(Kullanici k, int? id)
		{

			#region 1. YOl
			//if (id is null)
			//	return RedirectToAction(nameof(Index));

			//if (k is null)
			//{
			//	return RedirectToAction(nameof(Index));
			//}

			//if (ModelState.IsValid == false)
			//{
			//	return View(k);
			//}

			//var kullaniciListe = _dataContext.Kullanici.Where(t => t.EMail == k.EMail).FirstOrDefault();
			//if (kullaniciListe != null)
			//{
			//	//gönerilen mail adresi zaten veritabanında varmış.
			//	ModelState.AddModelError("EMail", "Zaten bu mail adresi kullanılıyor");
			//	return View(k);
			//}

			//var kullaniciListe1 = _dataContext.Kullanici.Where(t => t.KullaniciKodu == k.KullaniciKodu).FirstOrDefault();
			//if (kullaniciListe1 != null)
			//{
			//	//gönerilen mail adresi zaten veritabanında varmış.
			//	ModelState.AddModelError("KullaniciKodu", "Bu kullanıcı kodu kullanılıyor");
			//	return View(k);
			//}

			//var dbuser = _dataContext.Kullanici.Where()

			//return View(edit); 
			#endregion

			if (id is null)
				return RedirectToAction(nameof(Index));

			if (k.Id != id)
				return RedirectToAction(nameof(Index));

			if (_dataContext.Kullanici.Any(e => e.Id == id) == false)
				return RedirectToAction(nameof(Index));

			if (_dataContext.Kullanici.Any(t => t.EMail == k.EMail.Trim() && t.Id != k.Id))
			{
				ModelState.AddModelError("EMail", "Güncellemek istediğiniz email daha önce kayıt edilmiş.");
				return View(k);
			}

			if (ModelState.IsValid)
			{
				try
				{
					var dbdekiData = _dataContext.Kullanici.FirstOrDefault(e => e.Id == id);

					dbdekiData.AdSoyad = k.AdSoyad;
					dbdekiData.EMail = k.EMail;
					dbdekiData.KullaniciKodu = k.KullaniciKodu;
					dbdekiData.KullaniciSifre = k.KullaniciSifre;
					dbdekiData.Yas = k.Yas;
					dbdekiData.Aktif = k.Aktif;

					_dataContext.Update(dbdekiData);
					_dataContext.SaveChanges();
				}
				catch (Exception e)
				{
					//loga yazılacak.
					ModelState.AddModelError("AdSoyad", $"Inner Exep. : {e.Message}");
					return View(k);
				}
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		public IActionResult Create(Kullanici k)
		{
			if (k is null)
			{
				//return RedirectToAction("Index");
				return RedirectToAction(nameof(Index));
			}

			if (ModelState.IsValid == false)
			{
				return View(k);
			}
			//Eğer kullanici tarafından gönderilen Kullanici modelindeki email bilgisi veritabanında var mı? kontrolü yapıyoruz.
			//Linq -> nesneler içerisinde arama/sorgulama yapmamıza yarayan betik işlemler kümesi.

			var kullaniciListe = _dataContext.Kullanici.Where(t => t.EMail == k.EMail).FirstOrDefault();
			if (kullaniciListe != null)
			{
				//gönerilen mail adresi zaten veritabanında varmış.
				ModelState.AddModelError("EMail", "Zaten bu mail adresi kullanılıyor");
				return View(k);
			}

			var kullaniciListe1 = _dataContext.Kullanici.Where(t => t.KullaniciKodu == k.KullaniciKodu).FirstOrDefault();
			if (kullaniciListe1 != null)
			{
				//gönerilen mail adresi zaten veritabanında varmış.
				ModelState.AddModelError("KullaniciKodu", "Bu kullanıcı kodu kullanılıyor");
				return View(k);
			}

			//_dataContext.Kullanici.Add(k);
			_dataContext.Add(k);
			_dataContext.SaveChanges();

			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public IActionResult Delete(int? id)
		{
			if (id is null)
				return RedirectToAction(nameof(Index));

			var edit = _dataContext.Kullanici.Where(e => e.Id == id).FirstOrDefault();
			if (edit is null)
				return RedirectToAction(nameof(Index));

			return View(edit);
		}

		[HttpPost, ActionName("DeleteConfirm")]
		[ValidateAntiForgeryToken]
		public IActionResult DeleteConfirm(int? id)
		{
			if (id != null)

			{
				try
				{
					var dbdekiData = _dataContext.Kullanici.FirstOrDefault(e => e.Id == id);
					if (dbdekiData is null)
					{
						return RedirectToAction(nameof(Index));
					}

					_dataContext.Remove(dbdekiData);
					_dataContext.SaveChanges();

					return RedirectToAction(nameof(Index));
				}
				catch (Exception e)
				{
					//loga yazılacak.
					ModelState.AddModelError("AdSoyad", $"Inner Exep. : {e.Message}");
					return View();
				}
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public IActionResult Detail(int? id)
		{
			if (id is null)
				return RedirectToAction(nameof(Index));

			var edit = _dataContext.Kullanici.Where(e => e.Id == id).FirstOrDefault();
			if (edit is null)
				return RedirectToAction(nameof(Index));

			return View(edit);
		}
	}
}

Views/Kullanici/Create.cshtml
@model intro_LoginExam_v1.Models.Kullanici

<style>
	.butonuSagaTasi
	{
		display:flex;
		justify-content:flex-end;
		/* padding:10px; */
		padding-right:3px;
		/* border:1px solid #ccc */
	}
</style>

<form asp-controller="Kullanici" asp-action="Create" method="post">

	<div class="mb-3">
		<label asp-for="AdSoyad" class="form-label">Adı ve Soyadı</label>
		<input asp-for="AdSoyad" class="form-control" />
		<span asp-validation-for="AdSoyad" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="EMail" class="form-label"></label>
		<input asp-for="EMail" type="email" class="form-control" />
		<span asp-validation-for="EMail" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciKodu" class="form-label"></label>
		<input asp-for="KullaniciKodu" class="form-control" />
		<span asp-validation-for="KullaniciKodu" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciSifre" class="form-label"></label>
		<input asp-for="KullaniciSifre" class="form-control" />
		<span asp-validation-for="KullaniciSifre" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Yas" class="form-label"></label>
		<input asp-for="Yas" class="form-control" />
		<span asp-validation-for="Yas" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Aktif" class="form-label"></label>
		<input asp-for="Aktif" class="form-check-input" />
	</div>

	<div class="mb-3">
		<label class="form-check-label">
			<input class="form-check-input" asp-for="Aktif" />
			@Html.DisplayNameFor(model => model.Aktif)
		</label>
	</div>
	<div class="butonuSagaTasi" >
		<a class="btn btn-secondary mr-5" asp-action="Index"><i class="fa fa-arrow-alt-circle-left"></i> Listeye geri dön</a>
	<button type="submit" class="btn btn-success">Kaydet</button>
	</div>
</form>

Views/Kullanici/Delete.cshtml
@model intro_LoginExam_v1.Models.Kullanici

<style>
	.butonuSagaTasi {
		display: flex;
		justify-content: flex-end;
		/* padding:10px; */
		padding-right: 3px;
		/* border:1px solid #ccc */
	}
</style>

<form asp-controller="Kullanici" asp-action="DeleteConfirm" method="post">
	<input  type="hidden" asp-for="Id"/>
	<div class="mb-3">
		<label asp-for="AdSoyad" class="form-label"> Adı ve Soyadı</label>
		<input asp-for="AdSoyad" class="form-control" readonly />
		<span asp-validation-for="AdSoyad" class="text-danger"> </span>
	</div>
	<div class="mb-3">
		<label asp-for="EMail" class="form-label"></label>
		<input asp-for="EMail" class="form-control" disabled />
		<span asp-validation-for="EMail" class="text-danger"> </span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciKodu" class="form-label"></label>
		<input asp-for="KullaniciKodu" class="form-control" disabled />
		<span asp-validation-for="KullaniciKodu" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciSifre" class="form-label"></label>
		<input asp-for="KullaniciSifre" class="form-control" disabled />
		<span asp-validation-for="KullaniciSifre" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Yas" class="form-label"></label>
		<input asp-for="Yas" class="form-control" disabled />
		<span asp-validation-for="Yas" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Aktif" class="form-label"></label>
		<input asp-for="Aktif" class="form-check-input" disabled />
	</div>
	<div class="butonuSagaTasi">
		<a class="btn btn-secondary mr-5" asp-action="Index"><i class="fa fa-arrow-alt-circle-left"></i> Listeye geri dön</a>
		<button type="submit" class="btn btn-danger">SİL</button>
	</div>

</form>

Views/Kullanici/Detail.cshtml
@model intro_LoginExam_v1.Models.Kullanici

<style>
	.butonuSagaTasi {
		display: flex;
		justify-content: flex-end;
		/* padding:10px; */
		padding-right: 3px;
		/* border:1px solid #ccc */
	}
</style>

<form asp-controller="Kullanici" asp-action="Detail" method="post">
	<input type="hidden" asp-for="Id" />
	<div class="mb-3">
		<label asp-for="AdSoyad" class="form-label"> Adı ve Soyadı</label>
		<input asp-for="AdSoyad" class="form-control" disabled />
		<span asp-validation-for="AdSoyad" class="text-danger"> </span>
	</div>
	<div class="mb-3">
		<label asp-for="EMail" class="form-label"></label>
		<input asp-for="EMail" class="form-control" disabled />
		<span asp-validation-for="EMail" class="text-danger"> </span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciKodu" class="form-label"></label>
		<input asp-for="KullaniciKodu" class="form-control" disabled />
		<span asp-validation-for="KullaniciKodu" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciSifre" class="form-label"></label>
		<input asp-for="KullaniciSifre" class="form-control" disabled />
		<span asp-validation-for="KullaniciSifre" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Yas" class="form-label"></label>
		<input asp-for="Yas" class="form-control" disabled />
		<span asp-validation-for="Yas" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Aktif" class="form-label"></label>
		<input asp-for="Aktif" class="form-check-input" disabled />
	</div>
	<div class="butonuSagaTasi">
		<a class="btn btn-secondary mr-5" asp-action="Index"><i class="fa fa-arrow-alt-circle-left"></i> Listeye geri dön</a>
	</div>

</form>

Views/Kullanici/Edit.cshtml
@model intro_LoginExam_v1.Models.Kullanici

<style>
	.butonuSagaTasi {
		display: flex;
		justify-content: flex-end;
		/* padding:10px; */
		padding-right: 3px;
		/* border:1px solid #ccc */
	}
</style>

<form asp-controller="Kullanici" asp-action="Edit" method="post"> 
	<div class="mb-3">
			<label asp-for="AdSoyad" class="form-label"> Adı ve Soyadı</label>
			<input asp-for="AdSoyad" class="form-control"/>
			<span asp-validation-for="AdSoyad" class="text-danger"> </span>
	</div>
	<div class="mb-3">
		<label asp-for="EMail" class="form-label"></label>
		<input asp-for="EMail" class="form-control" />
		<span asp-validation-for="EMail" class="text-danger"> </span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciKodu" class="form-label"></label>
		<input asp-for="KullaniciKodu" class="form-control" />
		<span asp-validation-for="KullaniciKodu" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="KullaniciSifre" class="form-label"></label>
		<input asp-for="KullaniciSifre" class="form-control" />
		<span asp-validation-for="KullaniciSifre" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Yas" class="form-label"></label>
		<input asp-for="Yas" class="form-control" />
		<span asp-validation-for="Yas" class="text-danger"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Aktif" class="form-label"></label>
		<input asp-for="Aktif" class="form-check-input" />
	</div>
	<div class="butonuSagaTasi">
		<a class="btn btn-secondary mr-5" asp-action="Index"><i class="fa fa-arrow-alt-circle-left"></i> Listeye geri dön</a>
		<button type="submit" class="btn btn-success">Kaydet</button>
	</div>

</form>

Views/Kullanici/Index.cshtml
@model IEnumerable<intro_LoginExam_v1.Models.Kullanici>

<div class="row">
	<div class="col-xxl-12">
		<div class="card card-xxl-stretch mb-5 mb-xl-8">
			<!--Card Header-->
			<div class="card-header border-0 mb-xl-8">
				<h3 class="card-title align-items-start flex-column">
					Kullanici Liste
				</h3>
				<div class="card-toolbar" data-bs-toogle="tooltip" data-bs-placement="top">
					<a asp-action="Create" class="btn btn-light-primary"><i class="fa fa-plus"></i> Yeni Kullanıcı</a>
				</div>
			</div>
			<div class="card-body py-3">
				<table class="table table-striped table-row-bordered gy-5 gs-7 dt-init">
					<thead>
						<tr>
							<th>İşlemler</th>
							<th>@Html.DisplayNameFor(Model => Model.AdSoyad)</th>
							<th>@Html.DisplayNameFor(Model => Model.EMail)</th>
							<th>@Html.DisplayNameFor(Model => Model.KullaniciKodu)</th>
							<th>@Html.DisplayNameFor(Model => Model.Yas)</th>
						</tr>
					</thead>
					<tbody>
						@foreach(var item in Model)
						{
							<tr>
								<td>
									<a asp-action="Edit" asp-route-id="@item.Id" data-toogle="tooltip" title="Düzenle"><i class="fa fa-text-height" aria-hidden="true"></i></a>
									<a asp-action="Detail" asp-route-id="@item.Id" data-toogle="tooltip" title="Detay Gör"><i class="fa fa-id-card" aria-hidden="true"></i></a>
									<a asp-action="Delete" asp-route-id="@item.Id" data-toogle="tooltip" title="Sil"><i class="fa fa-trash" aria-hidden="true"></i></a>
								</td>
								<td>@Html.DisplayFor(modelItem=>item.AdSoyad)</td>
								<td>@Html.DisplayFor(modelItem => item.EMail)</td>
								<td>@Html.DisplayFor(modelItem => item.KullaniciKodu)</td>
								<td>@Html.DisplayFor(modelItem => item.Yas)</td>
							</tr>
						}
					</tbody>
				</table>

			</div>
		</div>

	</div>
</div>